In [3]:
import numpy as np
import pandas as pd
from tqdm import tqdm
import random
import matplotlib.pyplot as plt
import seaborn as sns
import datetime
import os

from sklearn.metrics import roc_auc_score

import pickle
def dump_pkl(data, filename):
  with open(filename, 'wb') as handle:
    pickle.dump(data, handle, protocol=pickle.HIGHEST_PROTOCOL)

def load_pkl(filename):
  with open(filename, 'rb') as handle:
    data = pickle.load(handle)
  return data

In [12]:
!mkdir data data/preproc data/preproc/1hour

mkdir: data: File exists
mkdir: data/preproc: File exists
mkdir: data/preproc/1hour: File exists

In [3]:
stocks = ['TON-USDT',
          'NEAR-USDT',
         'BTC-USDT',
         'ETH-USDT',
         'ETC-USDT',
         #'XRP-USDT',
         'BNB-USDT',
         'SOL-USDT',
         'DOGE-USDT',
         'ADA-USDT',
         'TRX-USDT',
         'LINK-USDT', 
         #'AVAX-USDT', 
         #'SUI-USDT',
         #'XLM-USDT',
         'LTC-USDT',
         
         'SHIB-USDT',
         #'HBAR-USDT',
         'DOT-USDT',
         'BCH-USDT',
         'OP-USDT', 
         
         #'AAVE-USDT',
         'LDO-USDT',
         'ARB-USDT',
         'UNI-USDT',
         'ATOM-USDT', #26
         ]

len(stocks) * len(stocks)

400

In [6]:
#1hour

for ticker1 in tqdm(stocks):
    for ticker2 in stocks:
        if ticker1 != ticker2:
            df1 = load_pkl(f'./data/raw/1hour/{ticker1}.pkl')
            df2 = load_pkl(f'./data/raw/1hour/{ticker2}.pkl')

            df1['ticker1'] = df1['close']
            df2['ticker2'] = df2['close']
            df = df1.merge(df2, on='time', how='inner')[['time', 'ticker1', 'ticker2']]

            df['close_1hour'] = df['ticker1'] / df['ticker2']
            df['ticker'] = f'{ticker1}_{ticker2}'

            mask = df['time'] >= pd.Timestamp('2023-01-01')
            df = df.loc[mask, :].reset_index(drop=True)
            
            dump_pkl(df, f'./data/preproc/1hour/{ticker1}_{ticker2}.pkl')

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 11.64it/s]

In [8]:
df = load_pkl('./data/preproc/1hour/ADA-USDT_ARB-USDT.pkl')
df

                     time  ticker1  ticker2  close_1hour             ticker
0     2023-03-23 16:00:00  0.36683   1.1500     0.318983  ADA-USDT_ARB-USDT
1     2023-03-23 17:00:00  0.37771   1.2760     0.296011  ADA-USDT_ARB-USDT
2     2023-03-23 18:00:00  0.37925   1.3219     0.286898  ADA-USDT_ARB-USDT
3     2023-03-23 19:00:00  0.37962   1.3000     0.292015  ADA-USDT_ARB-USDT
4     2023-03-23 20:00:00  0.37663   1.2832     0.293508  ADA-USDT_ARB-USDT
...                   ...      ...      ...          ...                ...
18590 2025-05-06 06:00:00  0.66140   0.3109     2.127372  ADA-USDT_ARB-USDT
18591 2025-05-06 07:00:00  0.66310   0.3107     2.134213  ADA-USDT_ARB-USDT
18592 2025-05-06 08:00:00  0.65790   0.3078     2.137427  ADA-USDT_ARB-USDT
18593 2025-05-06 09:00:00  0.66300   0.3091     2.144937  ADA-USDT_ARB-USDT
18594 2025-05-06 10:00:00  0.66150   0.3085     2.144246  ADA-USDT_ARB-USDT

[18595 rows x 5 columns]

### 1. Load data

In [5]:
stocks = [elem.split('.')[0] for elem in os.listdir('./data/preproc/1hour/')]
#stocks
len(stocks)

380

In [13]:
# dfs_5min = []
dfs_1hour = []
# dfs_1day = []

#stocks = [elem.split('.')[0] for elem in os.listdir('./data/preproc/1hour/')]

for stock in tqdm(stocks):

    # df_5min = load_pkl(f"./data/preproc/5min/{stock}.pkl")
    df_1hour = load_pkl(f"./data/preproc/1hour/{stock}.pkl")
    # df_1day = load_pkl(f"./data/preproc/1day/{stock}.pkl")
    
    # dfs_5min += [df_5min.copy()]
    dfs_1hour += [df_1hour.copy()]
    # dfs_1day += [df_1day.copy()]
    



# df_5min = pd.concat(dfs_5min)
# df_1day = pd.concat(dfs_1day)
df_1hour = pd.concat(dfs_1hour)

# df_5min.reset_index(drop=True, inplace=True)
df_1hour.reset_index(drop=True, inplace=True)
# df_1day.reset_index(drop=True, inplace=True)

# df_5min.shape, df_1hour.shape, df_1day.shape
df_1hour.shape

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 380/380 [00:00<00:00, 1112.92it/s]

(7736420, 5)

In [15]:
# df_5min.head()

In [19]:
df_1hour

,time,ticker1,ticker2,close_1hour,ticker
0,2023-01-01 00:00:00,5.56700,1200.440,0.004637,LINK-USDT_ETH-USDT
1,2023-01-01 01:00:00,5.56800,1196.620,0.004653,LINK-USDT_ETH-USDT
2,2023-01-01 02:00:00,5.57300,1196.320,0.004658,LINK-USDT_ETH-USDT
3,2023-01-01 03:00:00,5.52900,1194.180,0.004630,LINK-USDT_ETH-USDT
4,2023-01-01 04:00:00,5.55900,1196.230,0.004647,LINK-USDT_ETH-USDT
...,...,...,...,...,...
7736415,2025-05-06 06:00:00,0.24760,13.596,0.018211,TRX-USDT_LINK-USDT
7736416,2025-05-06 07:00:00,0.24734,13.610,0.018173,TRX-USDT_LINK-USDT
7736417,2025-05-06 08:00:00,0.24644,13.495,0.018262,TRX-USDT_LINK-USDT
7736418,2025-05-06 09:00:00,0.24625,13.571,0.018145,TRX-USDT_LINK-USDT
7736419,2025-05-06 10:00:00,0.24607,13.529,0.018188,TRX-USDT_LINK-USDT

In [ ]:
# df_1day.head()

### 2. Preproc data

#### 2.2 Link data of different time-period

In [ ]:
# dfs_5min = []
# dfs_1hour = []
# dfs_1day = []

# #stocks = [elem.split('.')[0] for elem in os.listdir('./data/preproc/1hour/')]

# for stock in tqdm(stocks):
#     df_5min = load_pkl(f"./data/preproc/5min/{stock}.pkl")
#     df_1hour = load_pkl(f"./data/preproc/1hour/{stock}.pkl")
#     df_1day = load_pkl(f"./data/preproc/1day/{stock}.pkl")

#     #time_index 1hour
#     df_5min['date_hour_index'] = (df_5min['time'] - pd.Timedelta(minutes=55)).dt.floor('h')
    
#     #time_index 1day
#     df_5min['date_day_index'] = (df_5min['time'] - pd.Timedelta('26 hours 55 minutes')).dt.floor('d') + pd.Timedelta(hours=3)

    
 
#     dfs_5min += [df_5min.copy()]
#     dfs_1hour += [df_1hour.copy()]
#     dfs_1day += [df_1day.copy()]


# df_5min = pd.concat(dfs_5min)
# df_1day = pd.concat(dfs_1day)
# df_1hour = pd.concat(dfs_1hour)


# df_5min.reset_index(drop=True, inplace=True)
# df_1hour.reset_index(drop=True, inplace=True)
# df_1day.reset_index(drop=True, inplace=True)


# df_5min.shape, df_1hour.shape, df_1day.shape

In [ ]:
# #проверка глазами
# i = 68000+13*6 + 12*24*90 - 80
# df_5min.iloc[i:i+20]

In [ ]:
# df_1hour.head()

In [ ]:
# df_1day.head()

In [ ]:
# #link different time-step date

# df_1hour.reset_index(inplace=True)
# df_1hour = df_1hour.rename(columns={col : col+'_1hour' for col in df_1hour.columns if col not in ['ticker']})
# df = df_5min.merge(df_1hour, left_on=['date_hour_index', 'ticker'], right_on=['time_1hour', 'ticker'], how='left')

# df_1day.reset_index(inplace=True)
# df_1day = df_1day.rename(columns={col : col+'_1day' for col in df_1day.columns if col not in ['ticker']})
# df = df.merge(df_1day, left_on=['date_day_index', 'ticker'], right_on=['time_1day', 'ticker'], how='left')

# #Проверка что не наджоинилось лишнего
# assert df_5min.shape[0] == df.shape[0], 'Error: with join dimensions'

In [ ]:
# df

In [ ]:
# #Проверка, что данные все данные подтянулись
# print(f'Не подтянулсиь пар (ticker, time_1hour) к 5min (от 1hour): {df.loc[df['close_1hour'].isnull(), ['ticker', 'date_hour_index']].groupby(['ticker', 'date_hour_index']).count().shape[0]}  акций-часов')

# #Проверка, что данные все данные подтянулись
# print(f'Не подтянулсиь пар (ticker, time_1day) к 5min (от 1day): {df.loc[df['close_1day'].isnull(), ['ticker', 'date_day_index']].groupby(['ticker', 'date_day_index']).count().shape[0]}  акций-дней')

In [ ]:
# df.loc[df['close_1day'].isnull(), ['ticker', 'date_day_index']].groupby(['ticker', 'date_day_index']).count()

In [ ]:
# df['close_1hour'].isnull().mean(), df['close_1day'].isnull().mean()

In [ ]:
# df['ticker'].nunique()

In [ ]:
# df = df[['time', 'close', 'ticker', 'index_1hour', 'index_1day']]
# df

### 2.5 Feature engineering

In [21]:
del df

In [23]:
# df

In [25]:
df_1hour

,time,ticker1,ticker2,close_1hour,ticker
0,2023-01-01 00:00:00,5.56700,1200.440,0.004637,LINK-USDT_ETH-USDT
1,2023-01-01 01:00:00,5.56800,1196.620,0.004653,LINK-USDT_ETH-USDT
2,2023-01-01 02:00:00,5.57300,1196.320,0.004658,LINK-USDT_ETH-USDT
3,2023-01-01 03:00:00,5.52900,1194.180,0.004630,LINK-USDT_ETH-USDT
4,2023-01-01 04:00:00,5.55900,1196.230,0.004647,LINK-USDT_ETH-USDT
...,...,...,...,...,...
7736415,2025-05-06 06:00:00,0.24760,13.596,0.018211,TRX-USDT_LINK-USDT
7736416,2025-05-06 07:00:00,0.24734,13.610,0.018173,TRX-USDT_LINK-USDT
7736417,2025-05-06 08:00:00,0.24644,13.495,0.018262,TRX-USDT_LINK-USDT
7736418,2025-05-06 09:00:00,0.24625,13.571,0.018145,TRX-USDT_LINK-USDT
7736419,2025-05-06 10:00:00,0.24607,13.529,0.018188,TRX-USDT_LINK-USDT

In [27]:
# df_1day.head()

In [31]:
from sklearn.linear_model import LinearRegression

def calculate_exp_ma(data, window):
    alpha = 2 / (window + 1)
    coeffs = ((1 - alpha)**(np.arange(window)[::-1])) * (alpha)
    coeffs[0] /= alpha
    
    return data.rolling(window=window, min_periods=window).apply(lambda x: (x*coeffs).sum()).values


def calculate_bollinger_bands(data, window):
    """Calculate Bollinger Bands"""
    rolling_mean = data.rolling(window=window, min_periods=window).mean().values
    rolling_std = data.rolling(window=window, min_periods=window).std().values
    norm_rolling_std = rolling_std / (rolling_mean + np.finfo(np.float32).eps)

    num_of_std = 2
    lower_band_2std = rolling_mean - (rolling_std * num_of_std)
    upper_band_2std = rolling_mean + (rolling_std * num_of_std)
    
    num_of_std = 3
    lower_band_3std = rolling_mean - (rolling_std * num_of_std)
    upper_band_3std = rolling_mean + (rolling_std * num_of_std)
    
    
    return rolling_mean, rolling_std, norm_rolling_std, lower_band_2std, upper_band_2std, lower_band_3std, upper_band_3std

def calculate_rsi(data, window):
    """Calculate Relative Strength Index"""
    delta = data.diff()
    gain = delta.clip(lower=0)
    loss = -delta.clip(upper=0)
    avg_gain = gain.rolling(window=window, min_periods=window).mean()
    avg_loss = loss.rolling(window=window, min_periods=window).mean()
    rs = avg_gain / avg_loss
    rsi = 100 - (100 / (1 + rs))

    mask = avg_loss == 0
    rsi[mask] = 100
    
    return rsi.values

def calculate_roc(data, periods):
    """Calculate Rate of Change"""
    roc = (data - data.shift(periods)) / (data.shift(periods)+np.finfo(np.float32).eps)
    return roc



def calc_stats(data, window=None, feat_name=None):
    #mean, std
    rolling_mean, rolling_std, norm_rolling_std,\
    lower_band_2std, upper_band_2std, lower_band_3std, upper_band_3std = calculate_bollinger_bands(data, window)

    #mean_abs_pct
    mean_abs_pct = calculate_roc(data, 1).rolling(window=window, min_periods=window).apply(lambda x: x.abs().mean()).values
        
    #alpha
    alpha = data.rolling(window=window, min_periods=window).apply(lambda x: LinearRegression().fit(x.values.reshape(-1, 1), np.arange(x.shape[0])).coef_[0]).values

    #min, max
    rolling_min = data.rolling(window=window, min_periods=window).min().values
    rolling_max = data.rolling(window=window, min_periods=window).max().values
    
    #rsi
    rsi = calculate_rsi(data, window)
    
    #roc
    roc = calculate_roc(data, window).values
    # diff = data.diff(window).values

    #exp_ma
    exp_ma = calculate_exp_ma(data, window)
    
    df_features = pd.DataFrame({f'{feat_name}_ma' : rolling_mean,
                        f'{feat_name}_std' : rolling_std,
                        f'{feat_name}_norm_std' : norm_rolling_std,
                        f'{feat_name}_ma_low_2std' : lower_band_2std,
                        f'{feat_name}_ma_up_2std' : upper_band_2std,
                        f'{feat_name}_ma_low_3std' : lower_band_3std,
                        f'{feat_name}_ma_up_3std' : upper_band_3std, 

                        f'{feat_name}_mean_abs_pct' : mean_abs_pct,
                            
                        f'{feat_name}_alpha' : alpha,
                            
                        f'{feat_name}_min' : rolling_min,
                        f'{feat_name}_max' : rolling_max,
                        f'{feat_name}_rsi' : rsi,
                        f'{feat_name}_roc' : roc,
                        # f'{feat_name}_diff' : diff,
                        f'{feat_name}_expma' : exp_ma,
                        }).astype(np.float32)
    return df_features


def calc_stats_diff_1(data, feat_name=None):
    return pd.DataFrame({f'{feat_name}_roc' : calculate_roc(data, 1).values,
                        # f'{feat_name}_diff' : data.diff(1).values,
                        }).astype(np.float32)

def calc_levels(data, window=None, levels=None, feat_name=None):
    
    #уровни
    data_levels = []
    column_names = []
    for i in range(1, len(levels)):
        level_low = levels[i-1]
        level_high = levels[i]
        data_levels += [data.rolling(window=window, min_periods=window).apply(lambda x: (((1+level_low)*x.values[-1] < x.values) & (x.values <= (1+level_high)*x.values[-1])).sum()).values]
        data_levels += [data.rolling(window=window, min_periods=window).apply(lambda x: (((1-level_high)*x.values[-1] <= x.values) & (x.values < (1-level_low)*x.values[-1])).sum()).values]

        column_names += [f"{feat_name}_lvl_{1+level_low}-{1+level_high}"]
        column_names += [f"{feat_name}_lvl_-{1-level_high}-{1-level_low}"]
    df_levels = pd.DataFrame({column_names[i]:data_levels[i] for i in range(len(column_names))}).astype(np.float32)
    return df_levels

In [34]:
def calculate_features(df_ticker, postfix=None):
    dfs = [df_ticker]
    
    levels =      [0, 0.02, 0.03, 0.05, 0.08, 0.1,]
    # levels_btc =  [0, 0.02, 0.04, 0.06, 0.08, 0.1, 0.12]


    #w1
    df_close = calc_stats_diff_1(df_ticker[f'close{postfix}'], feat_name=f'close{postfix}_w1')
    #df_volume = calc_stats_diff_1(df_ticker[f'volume{postfix}'], feat_name=f'volume{postfix}_w1')
    #df_btc_close = calc_stats_diff_1(df_ticker[f'btc_close{postfix}'], feat_name=f'btc_close{postfix}_w1')
    assert df_ticker.shape[0] == df_close.shape[0], 'Error w1'
    dfs += [df_close.copy()]

    #w5
    window = 5
    df_close = calc_stats(df_ticker[f'close{postfix}'], window=window, feat_name=f'close{postfix}_w{window}')
    #df_volume = calc_stats(df_ticker[f'volume{postfix}'], window=window, feat_name=f'volume{postfix}_w{window}')
    #df_btc_close = calc_stats(df_ticker[f'btc_close{postfix}'], window=window, feat_name=f'btc_close{postfix}_w{window}')
    assert df_ticker.shape[0] == df_close.shape[0], f'Error w{window}'
    dfs += [df_close.copy()]
    
    #w10
    window = 10
    df_close = calc_stats(df_ticker[f'close{postfix}'], window=window, feat_name=f'close{postfix}_w{window}')
    #df_volume = calc_stats(df_ticker[f'volume{postfix}'], window=window, feat_name=f'volume{postfix}_w{window}')
    #df_btc_close = calc_stats(df_ticker[f'btc_close{postfix}'], window=window, feat_name=f'btc_close{postfix}_w{window}')
    assert df_ticker.shape[0] == df_close.shape[0], f'Error w{window}'
    dfs += [df_close.copy()]
    
    #w20
    window = 20
    df_close = calc_stats(df_ticker[f'close{postfix}'], window=window, feat_name=f'close{postfix}_w{window}')
    #df_volume = calc_stats(df_ticker[f'volume{postfix}'], window=window, feat_name=f'volume{postfix}_w{window}')
    #df_btc_close = calc_stats(df_ticker[f'btc_close{postfix}'], window=window, feat_name=f'btc_close{postfix}_w{window}')
    assert df_ticker.shape[0] == df_close.shape[0], f'Error w{window}'
    dfs += [df_close.copy()]
    
    #w30
    window = 30
    df_close = calc_stats(df_ticker[f'close{postfix}'], window=window, feat_name=f'close{postfix}_w{window}')
    #df_volume = calc_stats(df_ticker[f'volume{postfix}'], window=window, feat_name=f'volume{postfix}_w{window}')
    #df_btc_close = calc_stats(df_ticker[f'btc_close{postfix}'], window=window, feat_name=f'btc_close{postfix}_w{window}')
    df_close_levels = calc_levels(df_ticker[f'close{postfix}'], window=window, levels=levels, feat_name=f'close{postfix}_w{window}')
    #df_btc_close_levels = calc_levels(df_ticker[f'btc_close{postfix}'], window=window, levels=levels_btc, feat_name=f'btc_close{postfix}_w{window}')
    assert df_ticker.shape[0] == df_close.shape[0]== df_close_levels.shape[0], f'Error w{window}'
    dfs += [df_close.copy(), df_close_levels.copy()]
    
    #w60
    window = 60
    df_close = calc_stats(df_ticker[f'close{postfix}'], window=window, feat_name=f'close{postfix}_w{window}')
    #df_volume = calc_stats(df_ticker[f'volume{postfix}'], window=window, feat_name=f'volume{postfix}_w{window}')
    #df_btc_close = calc_stats(df_ticker[f'btc_close{postfix}'], window=window, feat_name=f'btc_close{postfix}_w{window}')
    assert df_ticker.shape[0] == df_close.shape[0], f'Error w{window}'
    dfs += [df_close.copy()]
    
    #w120
    window = 120
    df_close = calc_stats(df_ticker[f'close{postfix}'], window=window, feat_name=f'close{postfix}_w{window}')
    #df_volume = calc_stats(df_ticker[f'volume{postfix}'], window=window, feat_name=f'volume{postfix}_w{window}')
    #df_btc_close = calc_stats(df_ticker[f'btc_close{postfix}'], window=window, feat_name=f'btc_close{postfix}_w{window}')
    df_close_levels = calc_levels(df_ticker[f'close{postfix}'], window=window, levels=levels, feat_name=f'close{postfix}_w{window}')
    #df_btc_close_levels = calc_levels(df_ticker[f'btc_close{postfix}'], window=window, levels=levels_btc, feat_name=f'btc_close{postfix}_w{window}')
    assert df_ticker.shape[0] == df_close.shape[0]== df_close_levels.shape[0], f'Error w{window}'
    dfs += [df_close.copy(), df_close_levels.copy()]

    #w200
    window = 200
    df_close = calc_stats(df_ticker[f'close{postfix}'], window=window, feat_name=f'close{postfix}_w{window}')
    #df_volume = calc_stats(df_ticker[f'volume{postfix}'], window=window, feat_name=f'volume{postfix}_w{window}')
    #df_btc_close = calc_stats(df_ticker[f'btc_close{postfix}'], window=window, feat_name=f'btc_close{postfix}_w{window}')
    df_close_levels = calc_levels(df_ticker[f'close{postfix}'], window=window, levels=levels, feat_name=f'close{postfix}_w{window}')
    #df_btc_close_levels = calc_levels(df_ticker[f'btc_close{postfix}'], window=window, levels=levels_btc, feat_name=f'btc_close{postfix}_w{window}')
    assert df_ticker.shape[0] == df_close.shape[0]== df_close_levels.shape[0], f'Error w{window}'
    dfs += [df_close.copy(), df_close_levels.copy()]

   
    df = pd.concat(dfs, axis=1)
    assert (df_ticker.shape[0] == df.shape[0]) and (df.shape[1] == sum([elem.shape[1] for elem in dfs])), 'Error concat'

    return df

#### 5min

In [39]:
# dfs = []
# for ticker in tqdm(df['ticker'].unique()):
#     mask = np.array(df['ticker'] == ticker)
#     df_ticker = df.loc[mask].copy().reset_index()

#     df_ticker_fe = calculate_features(df_ticker, postfix='')
#     #dump_pkl(df_ticker_fe.copy(), f'tmp/{ticker}.pkl', )
    
#     dfs += [df_ticker_fe.copy()]

# df_fe = pd.concat(dfs).set_index('index')

In [41]:
# (df_fe['close'] == df['close']).all()

In [43]:
# df_fe.shape

In [45]:
# df_fe.head()

In [48]:
#pd.set_option('display.max_rows', 300)
# df_fe.dtypes

#### 1hour

In [53]:
df_1hour

,time,ticker1,ticker2,close_1hour,ticker
0,2023-01-01 00:00:00,5.56700,1200.440,0.004637,LINK-USDT_ETH-USDT
1,2023-01-01 01:00:00,5.56800,1196.620,0.004653,LINK-USDT_ETH-USDT
2,2023-01-01 02:00:00,5.57300,1196.320,0.004658,LINK-USDT_ETH-USDT
3,2023-01-01 03:00:00,5.52900,1194.180,0.004630,LINK-USDT_ETH-USDT
4,2023-01-01 04:00:00,5.55900,1196.230,0.004647,LINK-USDT_ETH-USDT
...,...,...,...,...,...
7736415,2025-05-06 06:00:00,0.24760,13.596,0.018211,TRX-USDT_LINK-USDT
7736416,2025-05-06 07:00:00,0.24734,13.610,0.018173,TRX-USDT_LINK-USDT
7736417,2025-05-06 08:00:00,0.24644,13.495,0.018262,TRX-USDT_LINK-USDT
7736418,2025-05-06 09:00:00,0.24625,13.571,0.018145,TRX-USDT_LINK-USDT
7736419,2025-05-06 10:00:00,0.24607,13.529,0.018188,TRX-USDT_LINK-USDT

In [55]:
# dfs = []
# for ticker in tqdm(df_1hour['ticker'].unique()):
#     mask = np.array(df_1hour['ticker'] == ticker)
#     df_ticker = df_1hour.loc[mask].copy().reset_index()

#     df_ticker_fe = calculate_features(df_ticker, postfix='_1hour')
    
#     dfs += [df_ticker_fe.copy()]

# df_1hour_fe = pd.concat(dfs).set_index('index')

In [57]:
from joblib import Parallel, delayed
import multiprocessing

def parallel_worker(df_ticker):
    df_ticker_fe = calculate_features(df_ticker, postfix='_1hour')
    
    ticker = df_ticker_fe['ticker'].iloc[0]
    dump_pkl(df_ticker_fe, f'./tmp/{ticker}.pkl')
    
    return True

num_cores = 6
res = Parallel(n_jobs=num_cores)(delayed(parallel_worker)(df_1hour.loc[df_1hour['ticker'] == ticker].reset_index()) for ticker in tqdm(df_1hour['ticker'].unique()))
res

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 380/380 [45:18<00:00,  7.15s/it]

[True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True]

In [242]:
df = load_pkl('./tmp/DOGE-USDT_TRX-USDT.pkl')
df

,index,time,ticker1,ticker2,close_1hour,ticker,close_1hour_w1_roc,close_1hour_w5_ma,close_1hour_w5_std,close_1hour_w5_norm_std,...,close_1hour_w200_lvl_1-1.02,close_1hour_w200_lvl_-0.98-1,close_1hour_w200_lvl_1.02-1.03,close_1hour_w200_lvl_-0.97-0.98,close_1hour_w200_lvl_1.03-1.05,close_1hour_w200_lvl_-0.95-0.97,close_1hour_w200_lvl_1.05-1.08,close_1hour_w200_lvl_-0.92-0.95,close_1hour_w200_lvl_1.08-1.1,close_1hour_w200_lvl_-0.9-0.92
0,41110,2023-01-01 00:00:00,0.07044,0.05459,1.290346,DOGE-USDT_TRX-USDT,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,41111,2023-01-01 01:00:00,0.07025,0.05441,1.291123,DOGE-USDT_TRX-USDT,0.000602,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,41112,2023-01-01 02:00:00,0.07018,0.05452,1.287234,DOGE-USDT_TRX-USDT,-0.003012,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,41113,2023-01-01 03:00:00,0.06981,0.05454,1.279978,DOGE-USDT_TRX-USDT,-0.005637,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,41114,2023-01-01 04:00:00,0.06992,0.05477,1.276611,DOGE-USDT_TRX-USDT,-0.002630,1.285058,0.006454,0.005023,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20550,61660,2025-05-06 06:00:00,0.16980,0.24760,0.685784,DOGE-USDT_TRX-USDT,0.006141,0.684422,0.003479,0.005082,...,32.0,8.0,21.0,0.0,47.0,0.0,84.0,0.0,7.0,0.0
20551,61661,2025-05-06 07:00:00,0.17017,0.24734,0.688000,DOGE-USDT_TRX-USDT,0.003233,0.684558,0.003630,0.005303,...,31.0,17.0,18.0,0.0,60.0,0.0,68.0,0.0,5.0,0.0
20552,61662,2025-05-06 08:00:00,0.16886,0.24644,0.685197,DOGE-USDT_TRX-USDT,-0.004074,0.684093,0.003289,0.004807,...,32.0,8.0,20.0,0.0,48.0,0.0,82.0,0.0,9.0,0.0
20553,61663,2025-05-06 09:00:00,0.16954,0.24625,0.688487,DOGE-USDT_TRX-USDT,0.004802,0.685813,0.002743,0.003999,...,33.0,21.0,15.0,0.0,60.0,0.0,66.0,0.0,4.0,0.0
20554,61664,2025-05-06 10:00:00,0.16932,0.24607,0.688097,DOGE-USDT_TRX-USDT,-0.000567,0.687113,0.001507,0.002193,...,32.0,19.0,18.0,0.0,60.0,0.0,65.0,0.0,5.0,0.0

In [248]:
df = load_pkl('./tmp/OP-USDT_ADA-USDT.pkl')
df

,index,time,ticker1,ticker2,close_1hour,ticker,close_1hour_w1_roc,close_1hour_w5_ma,close_1hour_w5_std,close_1hour_w5_norm_std,...,close_1hour_w200_lvl_1-1.02,close_1hour_w200_lvl_-0.98-1,close_1hour_w200_lvl_1.02-1.03,close_1hour_w200_lvl_-0.97-0.98,close_1hour_w200_lvl_1.03-1.05,close_1hour_w200_lvl_-0.95-0.97,close_1hour_w200_lvl_1.05-1.08,close_1hour_w200_lvl_-0.92-0.95,close_1hour_w200_lvl_1.08-1.1,close_1hour_w200_lvl_-0.9-0.92
0,20555,2023-01-01 00:00:00,0.9213,0.24791,3.716268,OP-USDT_ADA-USDT,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20556,2023-01-01 01:00:00,0.9174,0.24623,3.725785,OP-USDT_ADA-USDT,0.002561,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20557,2023-01-01 02:00:00,0.9165,0.24584,3.728034,OP-USDT_ADA-USDT,0.000604,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20558,2023-01-01 03:00:00,0.9146,0.24456,3.739778,OP-USDT_ADA-USDT,0.003150,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20559,2023-01-01 04:00:00,0.9135,0.24530,3.724011,OP-USDT_ADA-USDT,-0.004216,3.726775,0.008510,0.002283,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20550,41105,2025-05-06 06:00:00,0.6380,0.66140,0.964621,OP-USDT_ADA-USDT,0.000122,0.964725,0.002810,0.002913,...,37.0,7.0,13.0,2.0,13.0,0.0,29.0,0.0,19.0,0.0
20551,41106,2025-05-06 07:00:00,0.6340,0.66310,0.956115,OP-USDT_ADA-USDT,-0.008817,0.962169,0.003730,0.003876,...,31.0,4.0,12.0,0.0,21.0,0.0,24.0,0.0,23.0,0.0
20552,41107,2025-05-06 08:00:00,0.6311,0.65790,0.959264,OP-USDT_ADA-USDT,0.003294,0.961828,0.003939,0.004095,...,33.0,7.0,11.0,0.0,19.0,0.0,27.0,0.0,23.0,0.0
20553,41108,2025-05-06 09:00:00,0.6369,0.66300,0.960633,OP-USDT_ADA-USDT,0.001427,0.961027,0.003619,0.003765,...,33.0,8.0,14.0,0.0,16.0,0.0,29.0,0.0,21.0,0.0
20554,41109,2025-05-06 10:00:00,0.6341,0.66150,0.958579,OP-USDT_ADA-USDT,-0.002139,0.959843,0.003134,0.003265,...,36.0,5.0,11.0,0.0,20.0,0.0,27.0,0.0,22.0,0.0

# Load Data

In [6]:
stocks = [elem.split('.')[0] for elem in os.listdir('./data/preproc/1hour/')]
#stocks
len(stocks)

380

In [8]:
dfs = []
for ticker in tqdm(stocks):
    df_ticker = load_pkl(f'./tmp/{ticker}.pkl')
    dfs += [df_ticker.copy()]

df_1hour_fe = pd.concat(dfs).set_index('index')

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 380/380 [00:02<00:00, 143.37it/s]

In [ ]:
(df_1hour_fe['close_1hour'] == df_1hour['close_1hour']).all(), (df_1hour_fe.index.values == df_1hour.index.values).all()

In [11]:
df_1hour_fe

,time,ticker1,ticker2,close_1hour,ticker,close_1hour_w1_roc,close_1hour_w5_ma,close_1hour_w5_std,close_1hour_w5_norm_std,close_1hour_w5_ma_low_2std,...,close_1hour_w200_lvl_1-1.02,close_1hour_w200_lvl_-0.98-1,close_1hour_w200_lvl_1.02-1.03,close_1hour_w200_lvl_-0.97-0.98,close_1hour_w200_lvl_1.03-1.05,close_1hour_w200_lvl_-0.95-0.97,close_1hour_w200_lvl_1.05-1.08,close_1hour_w200_lvl_-0.92-0.95,close_1hour_w200_lvl_1.08-1.1,close_1hour_w200_lvl_-0.9-0.92
index,,,,,,,,,,,,,,,,,,,,,
0,2023-01-01 00:00:00,5.56700,1200.440,0.004637,LINK-USDT_ETH-USDT,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2023-01-01 01:00:00,5.56800,1196.620,0.004653,LINK-USDT_ETH-USDT,0.003372,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2023-01-01 02:00:00,5.57300,1196.320,0.004658,LINK-USDT_ETH-USDT,0.001149,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2023-01-01 03:00:00,5.52900,1194.180,0.004630,LINK-USDT_ETH-USDT,-0.006117,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2023-01-01 04:00:00,5.55900,1196.230,0.004647,LINK-USDT_ETH-USDT,0.003703,0.004645,0.000012,0.002487,0.004622,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7736415,2025-05-06 06:00:00,0.24760,13.596,0.018211,TRX-USDT_LINK-USDT,-0.002637,0.018253,0.000077,0.004239,0.018098,...,6.0,12.0,0.0,11.0,0.0,29.0,0.0,57.0,0.0,80.0
7736416,2025-05-06 07:00:00,0.24734,13.610,0.018173,TRX-USDT_LINK-USDT,-0.002078,0.018249,0.000081,0.004453,0.018087,...,12.0,10.0,0.0,11.0,0.0,29.0,0.0,62.0,0.0,72.0
7736417,2025-05-06 08:00:00,0.24644,13.495,0.018262,TRX-USDT_LINK-USDT,0.004852,0.018258,0.000079,0.004351,0.018099,...,4.0,16.0,0.0,5.0,0.0,30.0,0.0,57.0,0.0,77.0
7736418,2025-05-06 09:00:00,0.24625,13.571,0.018145,TRX-USDT_LINK-USDT,-0.006367,0.018210,0.000052,0.002830,0.018107,...,16.0,8.0,0.0,15.0,0.0,31.0,0.0,58.0,0.0,68.0
7736419,2025-05-06 10:00:00,0.24607,13.529,0.018188,TRX-USDT_LINK-USDT,0.002371,0.018196,0.000044,0.002407,0.018108,...,11.0,13.0,0.0,12.0,0.0,28.0,0.0,55.0,0.0,77.0

In [116]:
# pd.set_option('display.max_rows', 300)
# df_1hour_fe.dtypes

#### 1day

In [58]:
# dfs = []
# for ticker in tqdm(df_1day['ticker'].unique()):
#     mask = np.array(df_1day['ticker'] == ticker)
#     df_ticker = df_1day.loc[mask].copy().reset_index()

#     df_ticker_fe = calculate_features(df_ticker, postfix='_1day')
    
#     dfs += [df_ticker_fe.copy()]

# df_1day_fe = pd.concat(dfs).set_index('index')

In [59]:
# (df_1day_fe['close_1day'] == df_1day['close_1day']).all(), (df_1day_fe.index.values == df_1day_fe['index_1day'].values).all()

In [60]:
# df_1day_fe

In [124]:
# !mkdir data/feat_engin

In [61]:
# dump_pkl(df_fe, './data/feat_engin/df_fe.pkl')

In [126]:
# dump_pkl(df_1hour_fe, './data/feat_engin/df_1hour_fe.pkl')

In [62]:
# dump_pkl(df_1day_fe, './data/feat_engin/df_1day_fe.pkl')

### #Load data

In [128]:
# import numpy as np
# import pandas as pd
# from tqdm import tqdm
# import random
# import matplotlib.pyplot as plt
# import seaborn as sns
# import datetime
# import os
# import gc

# from sklearn.metrics import roc_auc_score

# import pickle
# def dump_pkl(data, filename):
#   with open(filename, 'wb') as handle:
#     pickle.dump(data, handle, protocol=pickle.HIGHEST_PROTOCOL)

# def load_pkl(filename):
#   with open(filename, 'rb') as handle:
#     data = pickle.load(handle)
#   return data

In [130]:
# df_fe = load_pkl('./data/feat_engin/df_fe.pkl')
#d f_1hour_fe = load_pkl('./data/feat_engin/df_1hour_fe.pkl')
# df_1day_fe = load_pkl('./data/feat_engin/df_1day_fe.pkl')

# df_fe.shape, df_1hour_fe.shape, df_1day_fe.shape,

### time features

In [13]:
#hour
df_1hour_fe['hour'] = df_1hour_fe['time'].dt.hour

#day
df_1hour_fe['day'] = df_1hour_fe['time'].dt.day

#day_of_week
df_1hour_fe['weekday'] = df_1hour_fe['time'].dt.dayofweek



#month
#df_fe['month'] = df_fe['time'].dt.month


#hour
# time_cyclic = (df_fe['time'] - pd.to_datetime(df_fe['time'].dt.date) - pd.Timedelta('10:00:00')) / pd.Timedelta('13:00:00')
# df_fe['sin_time_hour'] = np.sin(time_cyclic * 2 * np.pi)
# df_fe['cos_time_hour'] = np.cos(time_cyclic * 2 * np.pi)

#day of week
# day_of_week_cyclic = np.minimum(df_fe['time'].dt.dayofweek, 4) / 4
# df_fe['sin_time_weekday'] = np.sin(day_of_week_cyclic * 2 * np.pi)
# df_fe['cos_time_weekday'] = np.cos(day_of_week_cyclic * 2 * np.pi)

#day of month
# day_of_month_cyclic = df_1day_fe['time'].dt.day / 30
# df_1day_fe['sin_time_monthday'] = np.sin(day_of_month_cyclic * 2 * np.pi)
# df_1day_fe['cos_time_monthday'] = np.cos(day_of_month_cyclic * 2 * np.pi)

In [19]:
# df_fe.head()

In [15]:
df_1hour_fe.head()

,time,ticker1,ticker2,close_1hour,ticker,close_1hour_w1_roc,close_1hour_w5_ma,close_1hour_w5_std,close_1hour_w5_norm_std,close_1hour_w5_ma_low_2std,...,close_1hour_w200_lvl_-0.97-0.98,close_1hour_w200_lvl_1.03-1.05,close_1hour_w200_lvl_-0.95-0.97,close_1hour_w200_lvl_1.05-1.08,close_1hour_w200_lvl_-0.92-0.95,close_1hour_w200_lvl_1.08-1.1,close_1hour_w200_lvl_-0.9-0.92,hour,day,weekday
index,,,,,,,,,,,,,,,,,,,,,
0,2023-01-01 00:00:00,5.567,1200.44,0.004637,LINK-USDT_ETH-USDT,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1,6
1,2023-01-01 01:00:00,5.568,1196.62,0.004653,LINK-USDT_ETH-USDT,0.003372,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,6
2,2023-01-01 02:00:00,5.573,1196.32,0.004658,LINK-USDT_ETH-USDT,0.001149,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,1,6
3,2023-01-01 03:00:00,5.529,1194.18,0.004630,LINK-USDT_ETH-USDT,-0.006117,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,1,6
4,2023-01-01 04:00:00,5.559,1196.23,0.004647,LINK-USDT_ETH-USDT,0.003703,0.004645,0.000012,0.002487,0.004622,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,1,6

In [64]:
# df_1day_fe.head()

### Delete useless (dublicated) columns

In [151]:
#del df_1hour_fe['date_hour_index']

In [152]:
#del df_1day_fe['date_index']

### Absolute value columns

In [17]:
def flag_delete(col_name):
    if 'norm_std' in col_name:
        return False
    
    for stop_word in ['ma', 'std', 'diff', 'min', 'max']:
        if stop_word in col_name:
            return True
    return False

In [65]:
# cols_del_5min = [elem for elem in df_fe.columns if flag_delete(elem)]
# len(cols_del_5min), cols_del_5min

In [19]:
cols_del_1hour = [elem for elem in df_1hour_fe.columns if flag_delete(elem)]
len(cols_del_1hour), cols_del_1hour

(63,
 ['close_1hour_w5_ma',
  'close_1hour_w5_std',
  'close_1hour_w5_ma_low_2std',
  'close_1hour_w5_ma_up_2std',
  'close_1hour_w5_ma_low_3std',
  'close_1hour_w5_ma_up_3std',
  'close_1hour_w5_min',
  'close_1hour_w5_max',
  'close_1hour_w5_expma',
  'close_1hour_w10_ma',
  'close_1hour_w10_std',
  'close_1hour_w10_ma_low_2std',
  'close_1hour_w10_ma_up_2std',
  'close_1hour_w10_ma_low_3std',
  'close_1hour_w10_ma_up_3std',
  'close_1hour_w10_min',
  'close_1hour_w10_max',
  'close_1hour_w10_expma',
  'close_1hour_w20_ma',
  'close_1hour_w20_std',
  'close_1hour_w20_ma_low_2std',
  'close_1hour_w20_ma_up_2std',
  'close_1hour_w20_ma_low_3std',
  'close_1hour_w20_ma_up_3std',
  'close_1hour_w20_min',
  'close_1hour_w20_max',
  'close_1hour_w20_expma',
  'close_1hour_w30_ma',
  'close_1hour_w30_std',
  'close_1hour_w30_ma_low_2std',
  'close_1hour_w30_ma_up_2std',
  'close_1hour_w30_ma_low_3std',
  'close_1hour_w30_ma_up_3std',
  'close_1hour_w30_min',
  'close_1hour_w30_max',
  'close_1hour_w30_expma',
  'close_1hour_w60_ma',
  'close_1hour_w60_std',
  'close_1hour_w60_ma_low_2std',
  'close_1hour_w60_ma_up_2std',
  'close_1hour_w60_ma_low_3std',
  'close_1hour_w60_ma_up_3std',
  'close_1hour_w60_min',
  'close_1hour_w60_max',
  'close_1hour_w60_expma',
  'close_1hour_w120_ma',
  'close_1hour_w120_std',
  'close_1hour_w120_ma_low_2std',
  'close_1hour_w120_ma_up_2std',
  'close_1hour_w120_ma_low_3std',
  'close_1hour_w120_ma_up_3std',
  'close_1hour_w120_min',
  'close_1hour_w120_max',
  'close_1hour_w120_expma',
  'close_1hour_w200_ma',
  'close_1hour_w200_std',
  'close_1hour_w200_ma_low_2std',
  'close_1hour_w200_ma_up_2std',
  'close_1hour_w200_ma_low_3std',
  'close_1hour_w200_ma_up_3std',
  'close_1hour_w200_min',
  'close_1hour_w200_max',
  'close_1hour_w200_expma'])

In [66]:
# cols_del_1day = [elem for elem in df_1day_fe.columns if flag_delete(elem)]
# len(cols_del_1day), cols_del_1day

## Concat

In [67]:
# df_fe.columns.tolist()

In [68]:
# df_1hour_fe.columns.tolist()

In [69]:
# df_1day_fe.columns.tolist()

In [70]:
# df_fe.shape, df_1hour_fe.shape, df_1day_fe.shape

In [71]:
# df = df_fe.merge(df_1hour_fe, on=['index_1hour', 'ticker'], how='left')
# df.shape

In [72]:
# df = df.merge(df_1day_fe, on=['index_1day', 'ticker'], how='left')
# df.shape

In [73]:
# df

In [74]:
# df.loc[df['index_1hour'].isnull(), 'time'].dt.date.unique()

In [75]:
# df.loc[df['index_1day'].isnull(), 'time'].dt.date.unique()

In [175]:
# for col in tqdm(df.columns):
#     assert df[col].isnull().sum() == 0, f'Nulls {col}'
#     # if df[col].isnull().sum() != 0:
#     #     print(col, df[col].isnull().sum())

In [179]:
#df.loc[df['volume_w1_roc'].isnull()]

### Relative features

In [183]:
# groups_5min = [
#         #windows: 
#         #close: w1, w5, w10, w20, w30, w60, w120
#         #volume: w1, w5, w10, w20
#         #btc_close: w1, w5, w10, w20, w30, w60, w120
#          ['close_w1_roc', 'close_w5_alpha', 'close_w10_alpha', 'close_w20_alpha', 'close_w30_alpha', 'close_w60_alpha', 'close_w120_alpha'],
#          #['volume_w1_roc', 'volume_w5_alpha', 'volume_w10_alpha'],
#          #['btc_close_w1_roc', 'btc_close_w5_alpha', 'btc_close_w10_alpha', 'btc_close_w20_alpha', 'btc_close_w30_alpha', 'btc_close_w60_alpha', 'btc_close_w120_alpha'],
    
    
#          ['close_w1_roc', 'close_w5_roc', 'close_w10_roc', 'close_w20_roc', 'close_w30_roc', 'close_w60_roc', 'close_w120_roc'],
#          #['volume_w1_roc', 'volume_w5_roc', 'volume_w10_roc'],
#          #['btc_close_w1_roc', 'btc_close_w5_roc', 'btc_close_w10_roc', 'btc_close_w20_roc', 'btc_close_w30_roc', 'btc_close_w60_roc', 'btc_close_w120_roc'],

    
#          ['close_w5_mean_abs_pct', 'close_w10_mean_abs_pct', 'close_w20_mean_abs_pct', 'close_w30_mean_abs_pct', 'close_w60_mean_abs_pct', 'close_w120_mean_abs_pct'],
#          #['volume_w5_mean_abs_pct', 'volume_w10_mean_abs_pct'],
#          #['btc_close_w5_mean_abs_pct', 'btc_close_w10_mean_abs_pct', 'btc_close_w20_mean_abs_pct', 'btc_close_w30_mean_abs_pct', 'btc_close_w60_mean_abs_pct', 'btc_close_w120_mean_abs_pct'],


#          ['close_w5_std', 'close_w10_std', 'close_w20_std', 'close_w30_std', 'close_w60_std', 'close_w120_std'],
#          #['volume_w5_std', 'volume_w10_std'],
#          #['btc_close_w5_std', 'btc_close_w10_std', 'btc_close_w20_std', 'btc_close_w30_std', 'btc_close_w60_std', 'btc_close_w120_std'],


#          ['close_w5_norm_std', 'close_w10_norm_std', 'close_w20_norm_std', 'close_w30_norm_std', 'close_w60_norm_std', 'close_w120_norm_std'],
#          #['volume_w5_norm_std', 'volume_w10_norm_std'],
#          #['btc_close_w5_norm_std', 'btc_close_w10_norm_std', 'btc_close_w20_norm_std', 'btc_close_w30_norm_std', 'btc_close_w60_norm_std', 'btc_close_w120_norm_std'],


#          ['close_w5_rsi', 'close_w10_rsi', 'close_w20_rsi', 'close_w30_rsi', 'close_w60_rsi', 'close_w120_rsi'],
#          #['volume_w5_rsi', 'volume_w10_rsi'],
#          #['btc_close_w5_rsi', 'btc_close_w10_rsi', 'btc_close_w20_rsi', 'btc_close_w30_rsi', 'btc_close_w60_rsi', 'btc_close_w120_rsi'],


#          ['close', 'close_w5_ma', 'close_w10_ma', 'close_w20_ma', 'close_w30_ma', 'close_w60_ma', 'close_w120_ma'],
#          #['volume', 'volume_w5_ma', 'volume_w10_ma'],
#          #['btc_close', 'btc_close_w5_ma', 'btc_close_w10_ma', 'btc_close_w20_ma', 'btc_close_w30_ma', 'btc_close_w60_ma', 'btc_close_w120_ma'],


#          ['close', 'close_w5_expma', 'close_w10_expma', 'close_w20_expma', 'close_w30_expma', 'close_w60_expma', 'close_w120_expma'],
#          #['volume', 'volume_w5_expma', 'volume_w10_expma'],
#          #['btc_close', 'btc_close_w5_expma', 'btc_close_w10_expma', 'btc_close_w20_expma', 'btc_close_w30_expma', 'btc_close_w60_expma', 'btc_close_w120_expma'],


#          {'close' : ['close_w5_min', 'close_w10_min', 'close_w20_min', 'close_w30_min', 'close_w60_min', 'close_w120_min']},
#          #{'volume' : ['volume_w5_min', 'volume_w10_min']},
#          #{'btc_close' : ['btc_close_w5_min', 'btc_close_w10_min', 'btc_close_w20_min', 'btc_close_w30_min', 'btc_close_w60_min', 'btc_close_w120_min']},

    
#          {'close' : ['close_w5_max', 'close_w10_max', 'close_w20_max', 'close_w30_max', 'close_w60_max', 'close_w120_max']},
#          #{'volume' : ['volume_w5_max', 'volume_w10_max']},
#          #{'btc_close' : ['btc_close_w5_max', 'btc_close_w10_max', 'btc_close_w20_max', 'btc_close_w30_max', 'btc_close_w60_max', 'btc_close_w120_max']},



#         #w5
#          {'close' : [  'close_w5_ma_low_2std', 'close_w5_ma_up_2std', 'close_w5_ma_low_3std', 'close_w5_ma_up_3std']},
#          #{'volume' : [  'volume_w5_ma_low_2std', 'volume_w5_ma_up_2std', 'volume_w5_ma_low_3std', 'volume_w5_ma_up_3std']},
#          #{'btc_close' : [  'btc_close_w5_ma_low_2std', 'btc_close_w5_ma_up_2std', 'btc_close_w5_ma_low_3std', 'btc_close_w5_ma_up_3std']},
#         #w10
#          {'close' : [  'close_w10_ma_low_2std', 'close_w10_ma_up_2std', 'close_w10_ma_low_3std', 'close_w10_ma_up_3std']},
#          #{'volume' : [  'volume_w10_ma_low_2std', 'volume_w10_ma_up_2std', 'volume_w10_ma_low_3std', 'volume_w10_ma_up_3std']},
#          #{'btc_close' : [  'btc_close_w10_ma_low_2std', 'btc_close_w10_ma_up_2std', 'btc_close_w10_ma_low_3std', 'btc_close_w10_ma_up_3std']},
#         #w20
#          {'close' : [  'close_w20_ma_low_2std', 'close_w20_ma_up_2std', 'close_w20_ma_low_3std', 'close_w20_ma_up_3std']},
#          #{'btc_close' : [  'btc_close_w20_ma_low_2std', 'btc_close_w20_ma_up_2std', 'btc_close_w20_ma_low_3std', 'btc_close_w20_ma_up_3std']},
#         #w30
#          {'close' : [  'close_w30_ma_low_2std', 'close_w30_ma_up_2std', 'close_w30_ma_low_3std', 'close_w30_ma_up_3std']},
#          #{'btc_close' : [  'btc_close_w30_ma_low_2std', 'btc_close_w30_ma_up_2std', 'btc_close_w30_ma_low_3std', 'btc_close_w30_ma_up_3std']},
#         #w60
#          {'close' : [  'close_w60_ma_low_2std', 'close_w60_ma_up_2std', 'close_w60_ma_low_3std', 'close_w60_ma_up_3std']},
#          #{'btc_close' : [  'btc_close_w60_ma_low_2std', 'btc_close_w60_ma_up_2std', 'btc_close_w60_ma_low_3std', 'btc_close_w60_ma_up_3std']},
#         #w120
#          {'close' : [  'close_w120_ma_low_2std', 'close_w120_ma_up_2std', 'close_w120_ma_low_3std', 'close_w120_ma_up_3std']},
#          #{'btc_close' : [  'btc_close_w120_ma_low_2std', 'btc_close_w120_ma_up_2std', 'btc_close_w120_ma_low_3std', 'btc_close_w120_ma_up_3std']},


#         #w5
#         ['close_w5_min', 'close_w5_max'],
#         #['volume_w5_min', 'volume_w5_max'],
#         #['btc_close_w5_min', 'btc_close_w5_max'],
#         #w10
#         ['close_w10_min', 'close_w10_max'],
#         #['volume_w10_min', 'volume_w10_max'],
#         #['btc_close_w10_min', 'btc_close_w10_max'],
#         #w20
#         ['close_w20_min', 'close_w20_max'],
#         #['btc_close_w20_min', 'btc_close_w20_max'],
#         #w30
#         ['close_w30_min', 'close_w30_max'],
#         #['btc_close_w30_min', 'btc_close_w30_max'],
#         #w60
#         ['close_w60_min', 'close_w60_max'],
#         #['btc_close_w60_min', 'btc_close_w60_max'],
#         #w120
#         ['close_w120_min', 'close_w120_max'],
#         #['btc_close_w120_min', 'btc_close_w120_max'],
# ]

In [21]:
groups_1hour = [
        #windows: 
        #close: w1, w5, w10, w20, w30, w60, w120, w200

         ['close_1hour_w1_roc', 'close_1hour_w5_alpha', 'close_1hour_w10_alpha', 'close_1hour_w20_alpha', 'close_1hour_w30_alpha', 'close_1hour_w60_alpha', 'close_1hour_w120_alpha', 'close_1hour_w200_alpha'],
         #['volume_1hour_w1_roc', 'volume_1hour_w5_alpha', 'volume_1hour_w10_alpha'],
         #['btc_close_1hour_w1_roc', 'btc_close_1hour_w5_alpha', 'btc_close_1hour_w10_alpha', 'btc_close_1hour_w20_alpha', 'btc_close_1hour_w30_alpha', 'btc_close_1hour_w60_alpha', 'btc_close_1hour_w120_alpha'],
    
         ['close_1hour_w1_roc', 'close_1hour_w5_roc', 'close_1hour_w10_roc', 'close_1hour_w20_roc', 'close_1hour_w30_roc', 'close_1hour_w60_roc', 'close_1hour_w120_roc', 'close_1hour_w200_roc'],
         #['volume_1hour_w1_roc', 'volume_1hour_w5_roc', 'volume_1hour_w10_roc'],
         #['btc_close_1hour_w1_roc', 'btc_close_1hour_w5_roc', 'btc_close_1hour_w10_roc', 'btc_close_1hour_w20_roc', 'btc_close_1hour_w30_roc', 'btc_close_1hour_w60_roc', 'btc_close_1hour_w120_roc'],

         ['close_1hour_w5_mean_abs_pct', 'close_1hour_w10_mean_abs_pct', 'close_1hour_w20_mean_abs_pct', 'close_1hour_w30_mean_abs_pct', 'close_1hour_w60_mean_abs_pct', 'close_1hour_w120_mean_abs_pct', 'close_1hour_w200_mean_abs_pct'],
         #['volume_1hour_w5_mean_abs_pct', 'volume_1hour_w10_mean_abs_pct'],
         #['btc_close_1hour_w5_mean_abs_pct', 'btc_close_1hour_w10_mean_abs_pct', 'btc_close_1hour_w20_mean_abs_pct', 'btc_close_1hour_w30_mean_abs_pct', 'btc_close_1hour_w60_mean_abs_pct', 'btc_close_1hour_w120_mean_abs_pct'],


         ['close_1hour_w5_std', 'close_1hour_w10_std', 'close_1hour_w20_std', 'close_1hour_w30_std', 'close_1hour_w60_std', 'close_1hour_w120_std', 'close_1hour_w200_std'],
         #['volume_1hour_w5_std', 'volume_1hour_w10_std'],
         #['btc_close_1hour_w5_std', 'btc_close_1hour_w10_std', 'btc_close_1hour_w20_std', 'btc_close_1hour_w30_std', 'btc_close_1hour_w60_std', 'btc_close_1hour_w120_std'],


         ['close_1hour_w5_norm_std', 'close_1hour_w10_norm_std', 'close_1hour_w20_norm_std', 'close_1hour_w30_norm_std', 'close_1hour_w60_norm_std', 'close_1hour_w120_norm_std', 'close_1hour_w200_norm_std'],
         #['volume_1hour_w5_norm_std', 'volume_1hour_w10_norm_std'],
         #['btc_close_1hour_w5_norm_std', 'btc_close_1hour_w10_norm_std', 'btc_close_1hour_w20_norm_std', 'btc_close_1hour_w30_norm_std', 'btc_close_1hour_w60_norm_std', 'btc_close_1hour_w120_norm_std'],


         ['close_1hour_w5_rsi', 'close_1hour_w10_rsi', 'close_1hour_w20_rsi', 'close_1hour_w30_rsi', 'close_1hour_w60_rsi', 'close_1hour_w120_rsi', 'close_1hour_w200_rsi'],
         #['volume_1hour_w5_rsi', 'volume_1hour_w10_rsi'],
         #['btc_close_1hour_w5_rsi', 'btc_close_1hour_w10_rsi', 'btc_close_1hour_w20_rsi', 'btc_close_1hour_w30_rsi', 'btc_close_1hour_w60_rsi', 'btc_close_1hour_w120_rsi'],


         ['close_1hour', 'close_1hour_w5_ma', 'close_1hour_w10_ma', 'close_1hour_w20_ma', 'close_1hour_w30_ma', 'close_1hour_w60_ma', 'close_1hour_w120_ma', 'close_1hour_w200_ma'],
         #['volume', 'volume_1hour_w5_ma', 'volume_1hour_w10_ma'],
         #['btc_close', 'btc_close_1hour_w5_ma', 'btc_close_1hour_w10_ma', 'btc_close_1hour_w20_ma', 'btc_close_1hour_w30_ma', 'btc_close_1hour_w60_ma', 'btc_close_1hour_w120_ma'],


         ['close_1hour', 'close_1hour_w5_expma', 'close_1hour_w10_expma', 'close_1hour_w20_expma', 'close_1hour_w30_expma', 'close_1hour_w60_expma', 'close_1hour_w120_expma',  'close_1hour_w200_expma'],
         #['volume', 'volume_1hour_w5_expma', 'volume_1hour_w10_expma'],
         #['btc_close', 'btc_close_1hour_w5_expma', 'btc_close_1hour_w10_expma', 'btc_close_1hour_w20_expma', 'btc_close_1hour_w30_expma', 'btc_close_1hour_w60_expma', 'btc_close_1hour_w120_expma'],


         {'close_1hour' : ['close_1hour_w5_min', 'close_1hour_w10_min', 'close_1hour_w20_min', 'close_1hour_w30_min', 'close_1hour_w60_min', 'close_1hour_w120_min', 'close_1hour_w200_min']},
         #{'volume' : ['volume_1hour_w5_min', 'volume_1hour_w10_min']},
         #{'btc_close' : ['btc_close_1hour_w5_min', 'btc_close_1hour_w10_min', 'btc_close_1hour_w20_min', 'btc_close_1hour_w30_min', 'btc_close_1hour_w60_min', 'btc_close_1hour_w120_min']},

    
         {'close_1hour' : ['close_1hour_w5_max', 'close_1hour_w10_max', 'close_1hour_w20_max', 'close_1hour_w30_max', 'close_1hour_w60_max', 'close_1hour_w120_max', 'close_1hour_w200_max']},
         #{'volume' : ['volume_1hour_w5_max', 'volume_1hour_w10_max']},
         #{'btc_close' : ['btc_close_1hour_w5_max', 'btc_close_1hour_w10_max', 'btc_close_1hour_w20_max', 'btc_close_1hour_w30_max', 'btc_close_1hour_w60_max', 'btc_close_1hour_w120_max']},



        #w5
         {'close_1hour' : [  'close_1hour_w5_ma_low_2std', 'close_1hour_w5_ma_up_2std', 'close_1hour_w5_ma_low_3std', 'close_1hour_w5_ma_up_3std']},
         #{'volume' : [  'volume_1hour_w5_ma_low_2std', 'volume_1hour_w5_ma_up_2std', 'volume_1hour_w5_ma_low_3std', 'volume_1hour_w5_ma_up_3std']},
         #{'btc_close' : [  'btc_close_1hour_w5_ma_low_2std', 'btc_close_1hour_w5_ma_up_2std', 'btc_close_1hour_w5_ma_low_3std', 'btc_close_1hour_w5_ma_up_3std']},
        #w10
         {'close_1hour' : [  'close_1hour_w10_ma_low_2std', 'close_1hour_w10_ma_up_2std', 'close_1hour_w10_ma_low_3std', 'close_1hour_w10_ma_up_3std']},
         #{'volume' : [  'volume_1hour_w10_ma_low_2std', 'volume_1hour_w10_ma_up_2std', 'volume_1hour_w10_ma_low_3std', 'volume_1hour_w10_ma_up_3std']},
         #{'btc_close' : [  'btc_close_1hour_w10_ma_low_2std', 'btc_close_1hour_w10_ma_up_2std', 'btc_close_1hour_w10_ma_low_3std', 'btc_close_1hour_w10_ma_up_3std']},
        #w20
         {'close_1hour' : [  'close_1hour_w20_ma_low_2std', 'close_1hour_w20_ma_up_2std', 'close_1hour_w20_ma_low_3std', 'close_1hour_w20_ma_up_3std']},
         #{'btc_close' : [  'btc_close_1hour_w20_ma_low_2std', 'btc_close_1hour_w20_ma_up_2std', 'btc_close_1hour_w20_ma_low_3std', 'btc_close_1hour_w20_ma_up_3std']},
        #w30
         {'close_1hour' : [  'close_1hour_w30_ma_low_2std', 'close_1hour_w30_ma_up_2std', 'close_1hour_w30_ma_low_3std', 'close_1hour_w30_ma_up_3std']},
         #{'btc_close' : [  'btc_close_1hour_w30_ma_low_2std', 'btc_close_1hour_w30_ma_up_2std', 'btc_close_1hour_w30_ma_low_3std', 'btc_close_1hour_w30_ma_up_3std']},
        #w60
         {'close_1hour' : [  'close_1hour_w60_ma_low_2std', 'close_1hour_w60_ma_up_2std', 'close_1hour_w60_ma_low_3std', 'close_1hour_w60_ma_up_3std']},
         #{'btc_close' : [  'btc_close_1hour_w60_ma_low_2std', 'btc_close_1hour_w60_ma_up_2std', 'btc_close_1hour_w60_ma_low_3std', 'btc_close_1hour_w60_ma_up_3std']},
        #w120
         {'close_1hour' : [  'close_1hour_w120_ma_low_2std', 'close_1hour_w120_ma_up_2std', 'close_1hour_w120_ma_low_3std', 'close_1hour_w120_ma_up_3std']},
         #{'btc_close' : [  'btc_close_1hour_w120_ma_low_2std', 'btc_close_1hour_w120_ma_up_2std', 'btc_close_1hour_w120_ma_low_3std', 'btc_close_1hour_w120_ma_up_3std']},
        #w200
         {'close_1hour' : [  'close_1hour_w200_ma_low_2std', 'close_1hour_w200_ma_up_2std', 'close_1hour_w200_ma_low_3std', 'close_1hour_w200_ma_up_3std']},

        #w5
        ['close_1hour_w5_min', 'close_1hour_w5_max'],
        #['volume_1hour_w5_min', 'volume_1hour_w5_max'],
        #['btc_close_1hour_w5_min', 'btc_close_1hour_w5_max'],
        #w10
        ['close_1hour_w10_min', 'close_1hour_w10_max'],
        #['volume_1hour_w10_min', 'volume_1hour_w10_max'],
        #['btc_close_1hour_w10_min', 'btc_close_1hour_w10_max'],
        #w20
        ['close_1hour_w20_min', 'close_1hour_w20_max'],
        #['btc_close_1hour_w20_min', 'btc_close_1hour_w20_max'],
        #w30
        ['close_1hour_w30_min', 'close_1hour_w30_max'],
        #['btc_close_1hour_w30_min', 'btc_close_1hour_w30_max'],
        #w60
        ['close_1hour_w60_min', 'close_1hour_w60_max'],
        #['btc_close_1hour_w60_min', 'btc_close_1hour_w60_max'],
        #w120
        ['close_1hour_w120_min', 'close_1hour_w120_max'],
        #['btc_close_1hour_w120_min', 'btc_close_1hour_w120_max'],
        #w200
        ['close_1hour_w200_min', 'close_1hour_w200_max'],
]

In [23]:
# groups_1day= [
#         #windows: 
#         #close: w1, w5, w10, w20, w30, w60, w120
#         #volume: w1, w5, w10, w20
#         #btc_close: w1, w5, w10, w20, w30, w60, w120
#          ['close_1day_w1_roc', 'close_1day_w5_alpha', 'close_1day_w10_alpha', 'close_1day_w20_alpha', 'close_1day_w30_alpha', 'close_1day_w60_alpha', 'close_1day_w120_alpha'],
#          #['volume_1day_w1_roc', 'volume_1day_w5_alpha', 'volume_1day_w10_alpha'],
#          #['btc_close_1day_w1_roc', 'btc_close_1day_w5_alpha', 'btc_close_1day_w10_alpha', 'btc_close_1day_w20_alpha', 'btc_close_1day_w30_alpha', 'btc_close_1day_w60_alpha', 'btc_close_1day_w120_alpha'],
    
#          ['close_1day_w1_roc', 'close_1day_w5_roc', 'close_1day_w10_roc', 'close_1day_w20_roc', 'close_1day_w30_roc', 'close_1day_w60_roc', 'close_1day_w120_roc'],
#          #['volume_1day_w1_roc', 'volume_1day_w5_roc', 'volume_1day_w10_roc'],
#          #['btc_close_1day_w1_roc', 'btc_close_1day_w5_roc', 'btc_close_1day_w10_roc', 'btc_close_1day_w20_roc', 'btc_close_1day_w30_roc', 'btc_close_1day_w60_roc', 'btc_close_1day_w120_roc'],

#          ['close_1day_w5_mean_abs_pct', 'close_1day_w10_mean_abs_pct', 'close_1day_w20_mean_abs_pct', 'close_1day_w30_mean_abs_pct', 'close_1day_w60_mean_abs_pct', 'close_1day_w120_mean_abs_pct'],
#          #['volume_1day_w5_mean_abs_pct', 'volume_1day_w10_mean_abs_pct'],
#          #['btc_close_1day_w5_mean_abs_pct', 'btc_close_1day_w10_mean_abs_pct', 'btc_close_1day_w20_mean_abs_pct', 'btc_close_1day_w30_mean_abs_pct', 'btc_close_1day_w60_mean_abs_pct', 'btc_close_1day_w120_mean_abs_pct'],


#          ['close_1day_w5_std', 'close_1day_w10_std', 'close_1day_w20_std', 'close_1day_w30_std', 'close_1day_w60_std', 'close_1day_w120_std'],
#          #['volume_1day_w5_std', 'volume_1day_w10_std'],
#          #['btc_close_1day_w5_std', 'btc_close_1day_w10_std', 'btc_close_1day_w20_std', 'btc_close_1day_w30_std', 'btc_close_1day_w60_std', 'btc_close_1day_w120_std'],


#          ['close_1day_w5_norm_std', 'close_1day_w10_norm_std', 'close_1day_w20_norm_std', 'close_1day_w30_norm_std', 'close_1day_w60_norm_std', 'close_1day_w120_norm_std'],
#          #['volume_1day_w5_norm_std', 'volume_1day_w10_norm_std'],
#          #['btc_close_1day_w5_norm_std', 'btc_close_1day_w10_norm_std', 'btc_close_1day_w20_norm_std', 'btc_close_1day_w30_norm_std', 'btc_close_1day_w60_norm_std', 'btc_close_1day_w120_norm_std'],


#          ['close_1day_w5_rsi', 'close_1day_w10_rsi', 'close_1day_w20_rsi', 'close_1day_w30_rsi', 'close_1day_w60_rsi', 'close_1day_w120_rsi'],
#          #['volume_1day_w5_rsi', 'volume_1day_w10_rsi'],
#          #['btc_close_1day_w5_rsi', 'btc_close_1day_w10_rsi', 'btc_close_1day_w20_rsi', 'btc_close_1day_w30_rsi', 'btc_close_1day_w60_rsi', 'btc_close_1day_w120_rsi'],


#          ['close', 'close_1day_w5_ma', 'close_1day_w10_ma', 'close_1day_w20_ma', 'close_1day_w30_ma', 'close_1day_w60_ma', 'close_1day_w120_ma'],
#          #['volume', 'volume_1day_w5_ma', 'volume_1day_w10_ma'],
#          #['btc_close', 'btc_close_1day_w5_ma', 'btc_close_1day_w10_ma', 'btc_close_1day_w20_ma', 'btc_close_1day_w30_ma', 'btc_close_1day_w60_ma', 'btc_close_1day_w120_ma'],


#          ['close', 'close_1day_w5_expma', 'close_1day_w10_expma', 'close_1day_w20_expma', 'close_1day_w30_expma', 'close_1day_w60_expma', 'close_1day_w120_expma'],
#          #['volume', 'volume_1day_w5_expma', 'volume_1day_w10_expma',],
#          #['btc_close', 'btc_close_1day_w5_expma', 'btc_close_1day_w10_expma', 'btc_close_1day_w20_expma', 'btc_close_1day_w30_expma', 'btc_close_1day_w60_expma', 'btc_close_1day_w120_expma'],


#          {'close' : ['close_1day_w5_min', 'close_1day_w10_min', 'close_1day_w20_min', 'close_1day_w30_min', 'close_1day_w60_min', 'close_1day_w120_min']},
#          #{'volume' : ['volume_1day_w5_min', 'volume_1day_w10_min',]},
#          #{'btc_close' : ['btc_close_1day_w5_min', 'btc_close_1day_w10_min', 'btc_close_1day_w20_min', 'btc_close_1day_w30_min', 'btc_close_1day_w60_min', 'btc_close_1day_w120_min']},

    
#          {'close' : ['close_1day_w5_max', 'close_1day_w10_max', 'close_1day_w20_max', 'close_1day_w30_max', 'close_1day_w60_max', 'close_1day_w120_max']},
#          #{'volume' : ['volume_1day_w5_max', 'volume_1day_w10_max',]},
#          #{'btc_close' : ['btc_close_1day_w5_max', 'btc_close_1day_w10_max', 'btc_close_1day_w20_max', 'btc_close_1day_w30_max', 'btc_close_1day_w60_max', 'btc_close_1day_w120_max']},



#         #w5
#          {'close' : [  'close_1day_w5_ma_low_2std', 'close_1day_w5_ma_up_2std', 'close_1day_w5_ma_low_3std', 'close_1day_w5_ma_up_3std']},
#          #{'volume' : [  'volume_1day_w5_ma_low_2std', 'volume_1day_w5_ma_up_2std', 'volume_1day_w5_ma_low_3std', 'volume_1day_w5_ma_up_3std']},
#          #{'btc_close' : [  'btc_close_1day_w5_ma_low_2std', 'btc_close_1day_w5_ma_up_2std', 'btc_close_1day_w5_ma_low_3std', 'btc_close_1day_w5_ma_up_3std']},
#         #w10
#          {'close' : [  'close_1day_w10_ma_low_2std', 'close_1day_w10_ma_up_2std', 'close_1day_w10_ma_low_3std', 'close_1day_w10_ma_up_3std']},
#          #{'volume' : [  'volume_1day_w10_ma_low_2std', 'volume_1day_w10_ma_up_2std', 'volume_1day_w10_ma_low_3std', 'volume_1day_w10_ma_up_3std']},
#          #{'btc_close' : [  'btc_close_1day_w10_ma_low_2std', 'btc_close_1day_w10_ma_up_2std', 'btc_close_1day_w10_ma_low_3std', 'btc_close_1day_w10_ma_up_3std']},
#         #w20
#          {'close' : [  'close_1day_w20_ma_low_2std', 'close_1day_w20_ma_up_2std', 'close_1day_w20_ma_low_3std', 'close_1day_w20_ma_up_3std']},
#          #{'btc_close' : [  'btc_close_1day_w20_ma_low_2std', 'btc_close_1day_w20_ma_up_2std', 'btc_close_1day_w20_ma_low_3std', 'btc_close_1day_w20_ma_up_3std']},
#         #w30
#          {'close' : [  'close_1day_w30_ma_low_2std', 'close_1day_w30_ma_up_2std', 'close_1day_w30_ma_low_3std', 'close_1day_w30_ma_up_3std']},
#          #{'btc_close' : [  'btc_close_1day_w30_ma_low_2std', 'btc_close_1day_w30_ma_up_2std', 'btc_close_1day_w30_ma_low_3std', 'btc_close_1day_w30_ma_up_3std']},
#         #w60
#          {'close' : [  'close_1day_w60_ma_low_2std', 'close_1day_w60_ma_up_2std', 'close_1day_w60_ma_low_3std', 'close_1day_w60_ma_up_3std']},
#          #{'btc_close' : [  'btc_close_1day_w60_ma_low_2std', 'btc_close_1day_w60_ma_up_2std', 'btc_close_1day_w60_ma_low_3std', 'btc_close_1day_w60_ma_up_3std']},
#         #w120
#          {'close' : [  'close_1day_w120_ma_low_2std', 'close_1day_w120_ma_up_2std', 'close_1day_w120_ma_low_3std', 'close_1day_w120_ma_up_3std']},
#          #{'btc_close' : [  'btc_close_1day_w120_ma_low_2std', 'btc_close_1day_w120_ma_up_2std', 'btc_close_1day_w120_ma_low_3std', 'btc_close_1day_w120_ma_up_3std']},


#         #w5
#         ['close_1day_w5_min', 'close_1day_w5_max'],
#         #['volume_1day_w5_min', 'volume_1day_w5_max'],
#         #['btc_close_1day_w5_min', 'btc_close_1day_w5_max'],
#         #w10
#         ['close_1day_w10_min', 'close_1day_w10_max'],
#         #['volume_1day_w10_min', 'volume_1day_w10_max'],
#         #['btc_close_1day_w10_min', 'btc_close_1day_w10_max'],
#         #w20
#         ['close_1day_w20_min', 'close_1day_w20_max'],
#         #['btc_close_1day_w20_min', 'btc_close_1day_w20_max'],
#         #w30
#         ['close_1day_w30_min', 'close_1day_w30_max'],
#         #['btc_close_1day_w30_min', 'btc_close_1day_w30_max'],
#         #w60
#         ['close_1day_w60_min', 'close_1day_w60_max'],
#         #['btc_close_1day_w60_min', 'btc_close_1day_w60_max'],
#         #w120
#         ['close_1day_w120_min', 'close_1day_w120_max'],
#         #['btc_close_1day_w120_min', 'btc_close_1day_w120_max'],
# ]

In [26]:
def uniq_pairs(cols):
    pairs = []
    for i in range(len(cols)-1):
        for j in range(i+1, len(cols)):
            pairs += [(cols[i], cols[j])]
    return pairs

def calc_relative_features(df, groups):
    for group in tqdm(groups):
        if type(group) == list:
            pairs = uniq_pairs(group)
            for pair in pairs:
                new_col = f'{pair[0]}/{pair[1]}'
                df[new_col] = df[pair[0]] / (df[pair[1]] + np.finfo(np.float32).eps)

        if type(group) == dict:
            pair1 = list(group.keys())[0]
            for pair0 in group[pair1]:
                new_col = f'{pair0}/{pair1}'
                df[new_col] = df[pair0] / (df[pair1] + np.finfo(np.float32).eps)

    return df

In [28]:
import warnings
warnings.filterwarnings('ignore')

In [31]:
# print(df.shape)
# calc_relative_features(df, groups_5min)
# df.shape

In [34]:
print(df_1hour_fe.shape)
calc_relative_features(df_1hour_fe, groups_1hour)
df_1hour_fe.shape

(7736420, 137)

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 24/24 [00:11<00:00,  2.12it/s]

(7736420, 382)

In [36]:
# print(df.shape)
# calc_relative_features(df, groups_1day)
# df.shape

In [39]:
# for col in tqdm(df.columns):
#     assert df[col].isnull().sum() == 0, f'Nulls {col}'

### Delete absolute valu columns

In [42]:
# len(cols_del_5min), len(cols_del_1hour), len(cols_del_1day)
len(cols_del_1hour)

63

In [43]:
# print(df.shape)
# for col in cols_del_5min+cols_del_1hour+cols_del_1day:
#     del df[col]
# df.shape


print(df_1hour_fe.shape)
for col in cols_del_1hour:
    del df_1hour_fe[col]
df_1hour_fe.shape

(7736420, 382)

(7736420, 319)

In [50]:
1

1

### Resize time of dataframe

In [52]:
mask = df_1hour_fe['time'] >= pd.Timestamp('2023-10-01')
mask.sum(), mask.mean()

(5321140, 0.6878039196424186)

In [54]:
df_1hour_fe = df_1hour_fe.loc[mask, :]

In [55]:
df_1hour_fe.reset_index(drop=True, inplace=True)

### and resize dtypes

In [56]:
df_1hour_fe.head()

,time,ticker1,ticker2,close_1hour,ticker,close_1hour_w1_roc,close_1hour_w5_norm_std,close_1hour_w5_mean_abs_pct,close_1hour_w5_alpha,close_1hour_w5_rsi,...,close_1hour_w200_ma_up_2std/close_1hour,close_1hour_w200_ma_low_3std/close_1hour,close_1hour_w200_ma_up_3std/close_1hour,close_1hour_w5_min/close_1hour_w5_max,close_1hour_w10_min/close_1hour_w10_max,close_1hour_w20_min/close_1hour_w20_max,close_1hour_w30_min/close_1hour_w30_max,close_1hour_w60_min/close_1hour_w60_max,close_1hour_w120_min/close_1hour_w120_max,close_1hour_w200_min/close_1hour_w200_max
0,2023-10-01 00:00:00,8.125,1674.34,0.004853,LINK-USDT_ETH-USDT,-0.000212,0.001655,0.001952,-76809.179688,37.773579,...,1.017613,0.858567,1.049422,0.996295,0.992175,0.979237,0.957690,0.941715,0.935259,0.867259
1,2023-10-01 01:00:00,8.182,1675.00,0.004885,LINK-USDT_ETH-USDT,0.006618,0.002966,0.003229,55649.933594,63.815258,...,1.010994,0.854461,1.042301,0.993400,0.992175,0.979237,0.957690,0.941715,0.935259,0.867780
2,2023-10-01 02:00:00,8.189,1670.88,0.004901,LINK-USDT_ETH-USDT,0.003323,0.004249,0.003463,53617.660156,78.713341,...,1.007771,0.853115,1.038703,0.990110,0.989161,0.977100,0.972409,0.939660,0.933219,0.865887
3,2023-10-01 03:00:00,8.248,1673.97,0.004927,LINK-USDT_ETH-USDT,0.005345,0.006522,0.003794,48150.113281,80.617393,...,1.002625,0.849995,1.033151,0.984846,0.984845,0.971905,0.967239,0.934664,0.928257,0.869934
4,2023-10-01 04:00:00,8.163,1673.85,0.004877,LINK-USDT_ETH-USDT,-0.010234,0.005686,0.005147,29338.947266,59.163799,...,1.013116,0.860112,1.043716,0.984846,0.984845,0.971905,0.967239,0.934664,0.928257,0.876473

In [60]:
cols = df_1hour_fe.columns[5:]
cols

Index(['close_1hour_w1_roc', 'close_1hour_w5_norm_std',
       'close_1hour_w5_mean_abs_pct', 'close_1hour_w5_alpha',
       'close_1hour_w5_rsi', 'close_1hour_w5_roc', 'close_1hour_w10_norm_std',
       'close_1hour_w10_mean_abs_pct', 'close_1hour_w10_alpha',
       'close_1hour_w10_rsi',
       ...
       'close_1hour_w200_ma_up_2std/close_1hour',
       'close_1hour_w200_ma_low_3std/close_1hour',
       'close_1hour_w200_ma_up_3std/close_1hour',
       'close_1hour_w5_min/close_1hour_w5_max',
       'close_1hour_w10_min/close_1hour_w10_max',
       'close_1hour_w20_min/close_1hour_w20_max',
       'close_1hour_w30_min/close_1hour_w30_max',
       'close_1hour_w60_min/close_1hour_w60_max',
       'close_1hour_w120_min/close_1hour_w120_max',
       'close_1hour_w200_min/close_1hour_w200_max'],
      dtype='object', length=314)

In [62]:
for col in tqdm(cols):
    try:
        df_1hour_fe[col] = df_1hour_fe[col].astype(np.float32)
    except:
        print(col)

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 314/314 [00:55<00:00,  5.64it/s]

## 2.6 Save data

In [46]:
!mkdir data/lgbm

In [64]:
#save
dump_pkl(df_1hour_fe, 'data/lgbm/data_1hour.pkl')

In [65]:
df_1hour_fe.shape

(5321140, 319)

In [66]:
df_1hour_fe.head()

,time,ticker1,ticker2,close_1hour,ticker,close_1hour_w1_roc,close_1hour_w5_norm_std,close_1hour_w5_mean_abs_pct,close_1hour_w5_alpha,close_1hour_w5_rsi,...,close_1hour_w200_ma_up_2std/close_1hour,close_1hour_w200_ma_low_3std/close_1hour,close_1hour_w200_ma_up_3std/close_1hour,close_1hour_w5_min/close_1hour_w5_max,close_1hour_w10_min/close_1hour_w10_max,close_1hour_w20_min/close_1hour_w20_max,close_1hour_w30_min/close_1hour_w30_max,close_1hour_w60_min/close_1hour_w60_max,close_1hour_w120_min/close_1hour_w120_max,close_1hour_w200_min/close_1hour_w200_max
0,2023-10-01 00:00:00,8.125,1674.34,0.004853,LINK-USDT_ETH-USDT,-0.000212,0.001655,0.001952,-76809.179688,37.773579,...,1.017613,0.858567,1.049422,0.996295,0.992175,0.979237,0.957690,0.941715,0.935259,0.867259
1,2023-10-01 01:00:00,8.182,1675.00,0.004885,LINK-USDT_ETH-USDT,0.006618,0.002966,0.003229,55649.933594,63.815258,...,1.010994,0.854461,1.042301,0.993400,0.992175,0.979237,0.957690,0.941715,0.935259,0.867780
2,2023-10-01 02:00:00,8.189,1670.88,0.004901,LINK-USDT_ETH-USDT,0.003323,0.004249,0.003463,53617.660156,78.713341,...,1.007771,0.853115,1.038703,0.990110,0.989161,0.977100,0.972409,0.939660,0.933219,0.865887
3,2023-10-01 03:00:00,8.248,1673.97,0.004927,LINK-USDT_ETH-USDT,0.005345,0.006522,0.003794,48150.113281,80.617393,...,1.002625,0.849995,1.033151,0.984846,0.984845,0.971905,0.967239,0.934664,0.928257,0.869934
4,2023-10-01 04:00:00,8.163,1673.85,0.004877,LINK-USDT_ETH-USDT,-0.010234,0.005686,0.005147,29338.947266,59.163799,...,1.013116,0.860112,1.043716,0.984846,0.984845,0.971905,0.967239,0.934664,0.928257,0.876473

In [212]:
#df.columns.tolist()

In [67]:
no_features = [
 'time',
 'close_1hour',
 'ticker1', 'ticker2',
 'ticker',
]

### 2.7 Save data to NN

In [217]:
#don't use NN

In [219]:
# df_fe.head()

In [220]:
# df_1day_fe.head()

In [221]:
# df_fe.shape, df_1day_fe.shape

In [222]:
# dump_pkl(df_fe, 'data/feat_engin/lgbm/data_1hour.pkl')
# dump_pkl(df_1day_fe, 'data/feat_engin/lgbm/data_1day.pkl')

# TMP

In [1]:
import numpy as np
import pandas as pd
from tqdm import tqdm
import random
import matplotlib.pyplot as plt
import seaborn as sns
import datetime
import os

from sklearn.metrics import roc_auc_score

import pickle
def dump_pkl(data, filename):
  with open(filename, 'wb') as handle:
    pickle.dump(data, handle, protocol=pickle.HIGHEST_PROTOCOL)

def load_pkl(filename):
  with open(filename, 'rb') as handle:
    data = pickle.load(handle)
  return data

In [76]:
#df = load_pkl('data/lgbm/data_1hour.pkl')
df = df_1hour_fe

#### uniq_1

In [83]:
no_analyze = [
 'time',
 # 'close_1hour',
 # 'ticker1', 'ticker2',
 'ticker',
]

In [86]:
# df_tmp = df[df.columns[~df.columns.isin(no_analyze)]].mean().reset_index()

df_tmp = []
for col in tqdm(df.columns[~df.columns.isin(no_analyze)]):
    df_tmp += [df[col].mean()]

df_tmp = pd.DataFrame({'index' : df.columns[~df.columns.isin(no_analyze)],
                      0 : df_tmp})

df_tmp

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 317/317 [00:01<00:00, 160.86it/s]

                                         index             0
0                                      ticker1  3.534420e+03
1                                      ticker2  3.534420e+03
2                                  close_1hour  1.193328e+07
3                           close_1hour_w1_roc  3.764103e-05
4                      close_1hour_w5_norm_std  6.278286e-03
..                                         ...           ...
312    close_1hour_w20_min/close_1hour_w20_max  9.464447e-01
313    close_1hour_w30_min/close_1hour_w30_max  9.351679e-01
314    close_1hour_w60_min/close_1hour_w60_max  9.100532e-01
315  close_1hour_w120_min/close_1hour_w120_max  8.751103e-01
316  close_1hour_w200_min/close_1hour_w200_max  8.415943e-01

[317 rows x 2 columns]

In [87]:
df_tmp[df_tmp[0].isnull()]

Empty DataFrame
Columns: [index, 0]
Index: []

In [88]:
df_tmp.groupby(0).index.unique()[df_tmp.groupby(0).index.nunique()>1]

0
0.986771    [close_1hour/close_1hour_w10_expma, close_1hou...
Name: index, dtype: object

In [89]:
df_tmp.groupby(0).index.unique()[df_tmp.groupby(0).index.nunique()>1].values

array([array(['close_1hour/close_1hour_w10_expma',
              'close_1hour_w5_expma/close_1hour_w30_expma'], dtype=object)],
      dtype=object)

In [ ]:
#df[['volume/volume_1hour_w5_ma', 'volume/volume_1hour_w5_expma']]

#### uniq_2

In [94]:
#df_tmp = df[df.columns[~df.columns.isin(no_analyze)]].nunique().reset_index()

df_tmp = []
for col in tqdm(df.columns[~df.columns.isin(no_analyze)]):
    df_tmp += [df[col].nunique()]

df_tmp = pd.DataFrame({'index' : df.columns[~df.columns.isin(no_analyze)],
                      0 : df_tmp})

df_tmp

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 317/317 [00:54<00:00,  5.77it/s]

                                         index        0
0                                      ticker1   109328
1                                      ticker2   109328
2                                  close_1hour  5280823
3                           close_1hour_w1_roc  5161340
4                      close_1hour_w5_norm_std  4880572
..                                         ...      ...
312    close_1hour_w20_min/close_1hour_w20_max  1150181
313    close_1hour_w30_min/close_1hour_w30_max  1147935
314    close_1hour_w60_min/close_1hour_w60_max  1028766
315  close_1hour_w120_min/close_1hour_w120_max   824127
316  close_1hour_w200_min/close_1hour_w200_max   661038

[317 rows x 2 columns]

In [95]:
df_tmp[df_tmp[0].isnull()]

Empty DataFrame
Columns: [index, 0]
Index: []

In [97]:
pd.set_option('display.max_rows', 120)
df_tmp.groupby(0).index.unique()[df_tmp.groupby(0).index.nunique()>1].reset_index()

        0                                              index
0      29  [close_1hour_w30_lvl_1.02-1.03, close_1hour_w3...
1      30  [close_1hour_w30_lvl_1-1.02, close_1hour_w30_l...
2     102  [close_1hour_w120_lvl_-0.97-0.98, close_1hour_...
3     112  [close_1hour_w120_lvl_1.03-1.05, close_1hour_w...
4     120  [close_1hour_w120_lvl_1-1.02, close_1hour_w120...
5     200  [close_1hour_w200_lvl_1-1.02, close_1hour_w200...
6  109328                                 [ticker1, ticker2]

In [101]:
i = 2
df_tmp.groupby(0).index.unique()[df_tmp.groupby(0).index.nunique()>1].index[i], df_tmp.groupby(0).index.unique()[df_tmp.groupby(0).index.nunique()>1].iloc[i]

(102,
 array(['close_1hour_w120_lvl_-0.97-0.98', 'close_1hour_w120_lvl_1.08-1.1'],
       dtype=object))